/**
 * Jugugu密钥Fast模式
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject2 model module.
 * @module model/InlineObject2
 * @version 1.0.0
 */
class InlineObject2 {
    /**
     * @member {String} phone
     * @type {String}
     */
    phone;
    /**
     * @member {String} account
     * @type {String}
     */
    account;
    /**
     * @member {String} secret
     * @type {String}
     */
    secret;
    /**
     * @member {Number} time
     * @type {Number}
     */
    time;
    /**
     * @member {String} token
     * @type {String}
     */
    token;
    /**
     * @member {String} paymentpass
     * @type {String}
     */
    paymentpass;
    /**
     * @member {String} openid
     * @type {String}
     */
    openid;
    /**
     * @member {String} from
     * @type {String}
     */
    from;
    /**
     * @member {Array.<CodegenProperty{openApiType='string', baseName='unsigntxjson', complexType='null', getter='getUnsigntxjson', setter='setUnsigntxjson', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='unsigntxjson', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['unsigntxjson'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, hasMore=false, required=false, deprecated=false, secondaryParam=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isListContainer=false, isMapContainer=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, _enum=null, allowableValues=null, items=null, mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Unsigntxjson', nameInSnakeCase='UNSIGNTXJSON', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} unsigntxjson
     * @type {Array.<CodegenProperty{openApiType='string', baseName='unsigntxjson', complexType='null', getter='getUnsigntxjson', setter='setUnsigntxjson', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='unsigntxjson', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['unsigntxjson'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, hasMore=false, required=false, deprecated=false, secondaryParam=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isListContainer=false, isMapContainer=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, _enum=null, allowableValues=null, items=null, mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Unsigntxjson', nameInSnakeCase='UNSIGNTXJSON', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    unsigntxjson;
    /**
     * @member {String} chaintype
     * @type {String}
     */
    chaintype;

    

    /**
     * Constructs a new <code>InlineObject2</code>.
     * @alias module:model/InlineObject2
     * @param phone {String} 
     * @param account {String} 通过接入jugugu申请
     * @param secret {String} 通过接入jugugu申请
     * @param time {Number} int64类型
     * @param token {String} 登录或者首次登录时获得
     * @param paymentpass {String} 可以自由设置也可以传“”空字符串，系统随机生成，建议让系统随机生成
     * @param openid {String} 项目方账户系统的唯一识别码，用于绑定登录jugugu系统
     * @param from {String} jugugu区块链地址，与phone对应
     * @param unsigntxjson {Array.<CodegenProperty{openApiType='string', baseName='unsigntxjson', complexType='null', getter='getUnsigntxjson', setter='setUnsigntxjson', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='unsigntxjson', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['unsigntxjson'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, hasMore=false, required=false, deprecated=false, secondaryParam=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isListContainer=false, isMapContainer=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, _enum=null, allowableValues=null, items=null, mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Unsigntxjson', nameInSnakeCase='UNSIGNTXJSON', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} 
     * @param chaintype {String} 这里填cfx即可
     */
    constructor(phone, account, secret, time, token, paymentpass, openid, from, unsigntxjson, chaintype) { 
        
        InlineObject2.initialize(this, phone, account, secret, time, token, paymentpass, openid, from, unsigntxjson, chaintype);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phone, account, secret, time, token, paymentpass, openid, from, unsigntxjson, chaintype) { 
        obj['phone'] = phone;
        obj['account'] = account;
        obj['secret'] = secret;
        obj['time'] = time;
        obj['token'] = token;
        obj['paymentpass'] = paymentpass;
        obj['openid'] = openid;
        obj['from'] = from;
        obj['unsigntxjson'] = unsigntxjson;
        obj['chaintype'] = chaintype;
    }

    /**
     * Constructs a <code>InlineObject2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject2} obj Optional instance to populate.
     * @return {module:model/InlineObject2} The populated <code>InlineObject2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject2();

            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'String');
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Number');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('paymentpass')) {
                obj['paymentpass'] = ApiClient.convertToType(data['paymentpass'], 'String');
            }
            if (data.hasOwnProperty('openid')) {
                obj['openid'] = ApiClient.convertToType(data['openid'], 'String');
            }
            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'String');
            }
            if (data.hasOwnProperty('unsigntxjson')) {
                obj['unsigntxjson'] = ApiClient.convertToType(data['unsigntxjson'], ['String']);
            }
            if (data.hasOwnProperty('chaintype')) {
                obj['chaintype'] = ApiClient.convertToType(data['chaintype'], 'String');
            }
        }
        return obj;
    }
}



export default InlineObject2;

