/**
 * Jugugu密钥Fast模式
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject3 model module.
 * @module model/InlineObject3
 * @version 1.0.0
 */
class InlineObject3 {
    /**
     * @member {String} phone
     * @type {String}
     */
    phone;
    /**
     * @member {String} account
     * @type {String}
     */
    account;
    /**
     * @member {String} secret
     * @type {String}
     */
    secret;
    /**
     * @member {Number} time
     * @type {Number}
     */
    time;
    /**
     * @member {String} randomtoken
     * @type {String}
     */
    randomtoken;
    /**
     * @member {String} openid
     * @type {String}
     */
    openid;

    

    /**
     * Constructs a new <code>InlineObject3</code>.
     * @alias module:model/InlineObject3
     * @param phone {String} 
     * @param account {String} 通过接入jugugu申请
     * @param secret {String} 通过接入jugugu申请
     * @param time {Number} int64类型
     * @param randomtoken {String} 可以由sha256函数随机产生，避免2分钟内重复，可用时间+其他唯一参数作为种子，防止重放攻击
     * @param openid {String} 项目方账户系统的唯一识别码，用于绑定登录jugugu系统
     */
    constructor(phone, account, secret, time, randomtoken, openid) { 
        
        InlineObject3.initialize(this, phone, account, secret, time, randomtoken, openid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phone, account, secret, time, randomtoken, openid) { 
        obj['phone'] = phone;
        obj['account'] = account;
        obj['secret'] = secret;
        obj['time'] = time;
        obj['randomtoken'] = randomtoken;
        obj['openid'] = openid;
    }

    /**
     * Constructs a <code>InlineObject3</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject3} obj Optional instance to populate.
     * @return {module:model/InlineObject3} The populated <code>InlineObject3</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject3();

            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'String');
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Number');
            }
            if (data.hasOwnProperty('randomtoken')) {
                obj['randomtoken'] = ApiClient.convertToType(data['randomtoken'], 'String');
            }
            if (data.hasOwnProperty('openid')) {
                obj['openid'] = ApiClient.convertToType(data['openid'], 'String');
            }
        }
        return obj;
    }
}



export default InlineObject3;

