/**
 * Jugugu密钥Fast模式
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2001 model module.
 * @module model/InlineResponse2001
 * @version 1.0.0
 */
class InlineResponse2001 {
    /**
     * @member {String} phone
     * @type {String}
     */
    phone;
    /**
     * @member {String} confluxaddress
     * @type {String}
     */
    confluxaddress;
    /**
     * @member {String} ethaddress
     * @type {String}
     */
    ethaddress;
    /**
     * @member {String} paymentpassword
     * @type {String}
     */
    paymentpassword;
    /**
     * @member {String} token
     * @type {String}
     */
    token;

    

    /**
     * Constructs a new <code>InlineResponse2001</code>.
     * @alias module:model/InlineResponse2001
     * @param phone {String} 
     * @param confluxaddress {String} 
     * @param ethaddress {String} 
     * @param paymentpassword {String} 
     * @param token {String} 
     */
    constructor(phone, confluxaddress, ethaddress, paymentpassword, token) { 
        
        InlineResponse2001.initialize(this, phone, confluxaddress, ethaddress, paymentpassword, token);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phone, confluxaddress, ethaddress, paymentpassword, token) { 
        obj['phone'] = phone;
        obj['confluxaddress'] = confluxaddress;
        obj['ethaddress'] = ethaddress;
        obj['paymentpassword'] = paymentpassword;
        obj['token'] = token;
    }

    /**
     * Constructs a <code>InlineResponse2001</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2001} obj Optional instance to populate.
     * @return {module:model/InlineResponse2001} The populated <code>InlineResponse2001</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2001();

            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('confluxaddress')) {
                obj['confluxaddress'] = ApiClient.convertToType(data['confluxaddress'], 'String');
            }
            if (data.hasOwnProperty('ethaddress')) {
                obj['ethaddress'] = ApiClient.convertToType(data['ethaddress'], 'String');
            }
            if (data.hasOwnProperty('paymentpassword')) {
                obj['paymentpassword'] = ApiClient.convertToType(data['paymentpassword'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }
}



export default InlineResponse2001;

