/**
 * Jugugu密钥Fast模式
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject model module.
 * @module model/InlineObject
 * @version 1.0.0
 */
class InlineObject {
    /**
     * @member {String} phone
     * @type {String}
     */
    phone;
    /**
     * @member {String} address
     * @type {String}
     */
    address;
    /**
     * @member {String} account
     * @type {String}
     */
    account;
    /**
     * @member {String} secret
     * @type {String}
     */
    secret;
    /**
     * @member {Number} time
     * @type {Number}
     */
    time;
    /**
     * @member {String} token
     * @type {String}
     */
    token;
    /**
     * @member {String} openid
     * @type {String}
     */
    openid;
    /**
     * @member {String} contract
     * @type {String}
     */
    contract;
    /**
     * @member {String} nftid
     * @type {String}
     */
    nftid;
    /**
     * @member {String} codestr
     * @type {String}
     */
    codestr;
    /**
     * @member {String} chaintype
     * @type {String}
     */
    chaintype;

    

    /**
     * Constructs a new <code>InlineObject</code>.
     * @alias module:model/InlineObject
     * @param phone {String} 
     * @param address {String} 
     * @param account {String} 通过接入jugugu申请
     * @param secret {String} 通过接入jugugu申请
     * @param time {Number} int64类型
     * @param token {String} 通过登录获得，首次注册时也会获得
     * @param openid {String} 项目方账户系统的唯一识别码，用于绑定登录jugugu系统
     * @param contract {String} 正式网合约：cfx:acb2027ht5t916d323zjfw9knrdj42fm8ay9n7e3x0  测试网合约：cfxtest:acbk50byfusjyh7494rm8yd8xhnkdh9jyetgadzem4
     * @param nftid {String} 
     * @param codestr {String} 
     * @param chaintype {String} 这里填cfx即可
     */
    constructor(phone, address, account, secret, time, token, openid, contract, nftid, codestr, chaintype) { 
        
        InlineObject.initialize(this, phone, address, account, secret, time, token, openid, contract, nftid, codestr, chaintype);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phone, address, account, secret, time, token, openid, contract, nftid, codestr, chaintype) { 
        obj['phone'] = phone;
        obj['address'] = address;
        obj['account'] = account;
        obj['secret'] = secret;
        obj['time'] = time;
        obj['token'] = token;
        obj['openid'] = openid;
        obj['contract'] = contract;
        obj['nftid'] = nftid;
        obj['codestr'] = codestr;
        obj['chaintype'] = chaintype;
    }

    /**
     * Constructs a <code>InlineObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject} obj Optional instance to populate.
     * @return {module:model/InlineObject} The populated <code>InlineObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject();

            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'String');
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Number');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('openid')) {
                obj['openid'] = ApiClient.convertToType(data['openid'], 'String');
            }
            if (data.hasOwnProperty('contract')) {
                obj['contract'] = ApiClient.convertToType(data['contract'], 'String');
            }
            if (data.hasOwnProperty('nftid')) {
                obj['nftid'] = ApiClient.convertToType(data['nftid'], 'String');
            }
            if (data.hasOwnProperty('codestr')) {
                obj['codestr'] = ApiClient.convertToType(data['codestr'], 'String');
            }
            if (data.hasOwnProperty('chaintype')) {
                obj['chaintype'] = ApiClient.convertToType(data['chaintype'], 'String');
            }
        }
        return obj;
    }
}



export default InlineObject;

